### ISSUE TITLE
Pb with Firefox-OS-Data-Exporter

### ISSUE THREAD

**Issue by Desiderius77** [laenion/Firefox-OS-Data-Exporter#1]
Hi
I have just found your site to save the calendar data of my FirefoxOS phone !

I have followed the instructions you give 

- adb pull /data/local/storage
  --> 2 Directories : default and permanent
 -- > in default the directory 1003+f+app+++calendar.gaiamobile.org
 --> cp -a 003+f+app+++calendar.gaiamobile.org ~/.mozilla/firefox/my_profile/storage/default/http+++digitalimagecorp.de
Then launch Firefox and go to http://digitalimagecorp.de/software/firefox-os-data-exporter/ffosexporter.html

Here I click on Export and many sections appear : Good !

I go to section "Events" where I see calendar data 
![events](https://user-images.githubusercontent.com/3873415/35673816-d6c2ac22-0742-11e8-8225-11c3ce508279.jpg)

Then I click on "Convert Data to ICS file" and ..........

nothing happens !

I have tried many times and reload the page and Firefox itself : same thing !

I am using Firefox 58 on a Linux laptop
Thanks by advance for your help

**Comment by laenion** [comment]
Hi Desiderius77,

I'll be attending FOSDEM this weekend, so I won't be able to have a look at it until Monday - I hope that's not too late for you.

**Comment by Desiderius77** [comment]
Hi Ignaz

Not at all ! I can wait to next week !

Godd FOSDEM

**Comment by laenion** [comment]
Firefox 58 removed Date.prototype.toLocaleFormat (https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Errors/Deprecated_toLocaleFormat), which I'm using extensively. I guess I'll have to write an own time format generator now... Will do that tomorrow.

**Comment by Desiderius77** [comment]
Effectively I succeeded using Firefox 57 !

It is a problem with Firefox 58 that you have found !

Thanks for fixing it

**Comment by laenion** [comment]
Thanks for reporting, the iCal exporter is now also compatible with Firefox versions >= 58.

Please export the calendar again with this version - I originally uploaded a version for testing yesterday which may have created invalid time entries.
